name: Update Global.list

on:
  workflow_dispatch: # 仅手动触发

jobs:
  update-global-list:
    runs-on: ubuntu-latest

    steps:
    - name: 检查代码
      uses: actions/checkout@v3

    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 提取并更新 Global.list
      run: python "Rule Collection/extract_global.py"


    - name: 提交更改
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add rule/Global.list
        git commit -m "更新 Global.list 文件"
        git push
