name: Parse Markdown and Generate Files

# 定义何时触发工作流
on:
  workflow_dispatch:  # 允许通过 GitHub 页面手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
      # 第一步：从仓库中检出最新代码
      - name: Checkout repository
        uses: actions/checkout@v3  # 使用官方的 checkout action，将代码克隆到运行器

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4  # 使用官方的 Python 设置 action
        with:
          python-version: '3.12.4'  # 选择合适的 Python 版本

      # 第三步：安装 requests 模块
      - name: Install requests
        run: |
          python -m pip install --upgrade pip  # 更新 pip 包管理器
          pip install requests  # 安装 requests 模块

      # 第四步：运行 parse_markdown.py 脚本
      - name: Run parse_markdown.py
        run: |
          python "Rule Collection/parse_markdown.py"  # 执行脚本
      
      # 在推送之前先拉取最新代码并合并
      - name: Pull latest changes from remote
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git pull origin master  # 拉取远程 master 分支的最新更改
  
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto-generated files from markdown"
          git push origin master  # 推送更改到远程 master 分支
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}