name: Sync Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点 UTC 运行
    
  # 手动触发工作流，可以通过 GitHub UI 手动运行
  workflow_dispatch:
  push:
    branches:
      - master  # 监听 master 分支

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出你的仓库代码
      - name: Checkout your repository
        uses: actions/checkout@v2

      # Step 2: 克隆目标仓库的代码
      - name: Clone the target repository
        run: |
          git clone https://github.com/blackmatrix7/ios_rule_script target_repo
          cd target_repo

          # 合并目标文件
          cat rule/QuantumultX/OpenAI/OpenAI.list >> ../merged_rules.txt
          echo "" >> ../merged_rules.txt
          cat rule/QuantumultX/OpenAI/Gemini.list >> ../merged_rules.txt
          echo "" >> ../merged_rules.txt

      # Step 3: 将合并后的文件移动到目标路径
      - name: Move merged rules to the target path
        run: |
          # 将合并后的规则文件移动到 'rule/AII.txt' 目标路径
          mv ../merged_rules.txt ../rule/AII.txt

      # Step 4: 提交和推送到 master 分支
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

          # 添加 'rule/AI.txt' 文件到暂存区
          git add rule/AII.txt
          
          # 提交更改
          git commit -m "Update AI.txt with rules from target repository"
          
          # 推送到 master 分支
          git push origin master
