name: Sync Rules

# 定义定时任务，每天凌晨2点运行（你可以根据需要调整时间）
on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨2点
  workflow_dispatch: # 允许手动触发

jobs:
  sync-rules:
    runs-on: ubuntu-latest

    steps:
    # 第一步，拉取你的仓库代码
    - name: Checkout My Repo
      uses: actions/checkout@v3
      with:
        repository: hwangzhun/Quantumult-X-Config
        path: my-repo

    # 第二步，拉取目标仓库的代码
    - name: Checkout Target Repo
      uses: actions/checkout@v3
      with:
        repository: blackmatrix7/ios_rule_script
        path: target-repo

    # 第三步，合并规则并增量更新到AI.list文件
    - name: Append new rules
      run: |
        # 目标文件路径
        OPENAI_FILE="target-repo/rule/QuantumultX/OpenAI/OpenAI.list"
        GEMINI_FILE="target-repo/rule/QuantumultX/Gemini/Gemini.list"
        AI_FILE="my-repo/rule/AI.list"

        # 检查目标文件是否存在
        if [ -f "$OPENAI_FILE" ]; then
          echo "OpenAI.list file found, appending to AI.list"
          echo -e "\n# OpenAI Rules\n$(cat $OPENAI_FILE)" >> $AI_FILE
        fi

        if [ -f "$GEMINI_FILE" ]; then
          echo "Gemini.list file found, appending to AI.list"
          echo -e "\n# Gemini Rules\n$(cat $GEMINI_FILE)" >> $AI_FILE
        fi

    # 第四步，将更新推送到你的仓库
    - name: Commit and Push Changes
      run: |
        cd my-repo
        git config user.name "GitHub Action"
        git config user.email "Action@github.com"
    
        # 拉取远程仓库的最新改动，并自动解决冲突
        git pull origin master --rebase || git rebase --continue
    
        # 添加并提交新的规则
        git add rule/AI.list
        git commit -m "例行更新 AI.list"
    
        # 推送更改到远程仓库
        git push origin master
