name: Sync AI Application Rule

on:
  schedule:
    - cron: '0 0 * * *' # 每小时执行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Checkout your own repository
    - name: Checkout Your Repository
      uses: actions/checkout@v3
      with:
        path: your-repo

    # Checkout the target repository
    - name: Checkout Target Repository
      uses: actions/checkout@v3
      with:
        repository: blackmatrix7/ios_rule_script
        path: target-repo

    # Merge rules from the target files to your file
    - name: Merge Rules
      run: |
        # 创建一个空的规则文件
        > your-repo/rule/AII.list

        # 添加 OpenAI.list 的规则并换行
        cat target-repo/rule/QuantumultX/OpenAI/OpenAI.list >> your-repo/rule/AI.list
        echo "" >> your-repo/rule/AII.list

        # 添加 Gemini.list 的规则并换行
        cat target-repo/rule/QuantumultX/Gemini/Gemini.list >> your-repo/rule/AI.list
        echo "" >> your-repo/rule/AII.list

    # 提交并将更改推送到您的存储库
    - name: Commit and Push
      run: |
        cd your-repo
        git config --global user.name "GitHub Action"
        git config --global user.email "Action@github.com"
        git add rule/AI.list
        git commit -m "Update AII.list with latest rules"
        git push https://x-access-token:${{ secrets.PAT }}@github.com/hwangzhun/Quantumult-X-Config.git
